### ISSUE TITLE
Few Additions

### ISSUE THREAD

**Issue by theRay1s** [adekmaulana/caligo#65]
Sir Please add ffmpeg Support 
And Direct Link module

**Comment by adekmaulana** [comment]
Currently working on it 😁

**Comment by theRay1s** [comment]
> Currently working on it 😁

For Direct link refrence

https://www.github.com/UsergeTeam/Userge/tree/alpha/userge%2Fplugins%2Futils%2Fdirect_links.py

**Comment by theRay1s** [comment]
> Currently working on it 😁

Sir Dogbin giving error 

Traceback (most recent call last):
  File "caligo/core/command_dispatcher.py", line 117, in on_command
    ret = await cmd.func(ctx)
  File "caligo/modules/debug.py", line 140, in cmd_dog
    async with self.bot.http.post("https://del.dog/documents", data=text) as resp:
  File "/opt/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/opt/venv/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/opt/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
ClientConnectorError: Cannot connect to host del.dog:443 ssl:default [Name does not resolve]

**Comment by adekmaulana** [comment]
> > Currently working on it grin
> 
> Sir Dogbin giving error
> 
> Traceback (most recent call last):
> File "caligo/core/command_dispatcher.py", line 117, in on_command
> ret = await cmd.func(ctx)
> File "caligo/modules/debug.py", line 140, in cmd_dog
> async with self.bot.http.post("https://del.dog/documents", data=text) as resp:
> File "/opt/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in **aenter**
> self._resp = await self._coro
> File "/opt/venv/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
> conn = await self._connector.connect(
> File "/opt/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
> proto = await self._create_connection(req, traces, timeout)
> File "/opt/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
> _, proto = await self._create_direct_connection(req, traces, timeout)
> File "/opt/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
> raise ClientConnectorError(req.connection_key, exc) from exc
> ClientConnectorError: Cannot connect to host del.dog:443 ssl:default [Name does not resolve]

yeah dogbin dead i think, will removed when i have time.
thanks for the info
